//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class IdleInputSource : IInputSource
{
	public IdleInputSource ()
	{

	}

	public void FrameStart()
	{

	}

	public InputState State
	{
		get
		{
			return new InputState();
		}
	}
}

