//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class MouseInputSource : IInputSource
{
	private InputState currentState = null;
	private Transform playerTransform;

	public MouseInputSource (Transform playerTransform)
	{
		this.playerTransform = playerTransform;
	}
	
	public void FrameStart(InputState previousState)
	{
		Ray mousePosition = Camera.main.ScreenPointToRay(Input.mousePosition);
		Vector3 playerPosition = playerTransform.position + new Vector3(0.0f, 1.0f, 0.0f);
		float distance = (playerPosition.z - mousePosition.origin.z) / mousePosition.direction.z;

		Vector3 aimDirection = (mousePosition.GetPoint(distance) - playerPosition).normalized;
		bool[] fireButtons = new bool[]{Input.GetButton("Fire0"), Input.GetButton("Fire1"), Input.GetButton("Fire2")};

		currentState = new InputState(previousState, Input.GetAxis("Horizontal"), Input.GetButton("Jump"), fireButtons, aimDirection, Time.time);
	}

	public InputState State
	{
		get
		{
			return currentState;
		}
	}
}

