//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;


public class InputRecording
{
	private List<InputState> inputStateHistory = new List<InputState>();

	public InputRecording()
	{

	}

	public void LogInput(InputState state)
	{
		inputStateHistory.Add(state);
	}

	public int Length
	{
		get
		{
			return inputStateHistory.Count;
		}
	}

	public InputState GetState(int index)
	{
		return inputStateHistory[index];
	}

	public static InputRecording Deserialize(SimpleJSON.JSONNode input)
	{
		InputState prev = null;

		InputRecording result = new InputRecording();

		foreach (SimpleJSON.JSONNode state in input.AsArray.Childs)
		{
			InputState current = InputState.Deserialize(state, prev);
			result.LogInput(current);
			prev = current;
		}

		return result;
	}

	public SimpleJSON.JSONNode Serialize()
	{
		SimpleJSON.JSONArray result = new SimpleJSON.JSONArray();
		foreach (InputState state in inputStateHistory)
		{
			result.Add(state.Serialize());
		}
		return result;
	}
}

public class RecordInputSource : IInputSource
{
	private InputState currentState = new InputState(null);
	private IInputSource inputSource;
	private InputRecording target;

	public RecordInputSource(InputRecording target, IInputSource inputSource)
	{
		this.target = target;
		this.inputSource = inputSource;
	}
	
	public void FrameStart(InputState previousState)
	{
		inputSource.FrameStart(previousState);
		currentState = inputSource.State;
		target.LogInput(currentState);
	}

	public InputState State
	{
		get
		{
			return currentState;
		}
	}
}

