//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;


public class InputRecording
{
	private List<InputState> inputStateHistory = new List<InputState>();

	public InputRecording()
	{

	}

	public void LogInput(InputState state)
	{
		inputStateHistory.Add(state);
	}

	public int Length
	{
		get
		{
			return inputStateHistory.Count;
		}
	}

	public InputState GetState(int index)
	{
		return inputStateHistory[index];
	}
}

public class RecordInputSource : IInputSource
{
	private InputState currentState = new InputState(null);
	private IInputSource inputSource;
	private InputRecording target;

	public RecordInputSource (InputRecording target, IInputSource inputSource)
	{
		this.target = target;
		this.inputSource = inputSource;
	}
	
	public void FrameStart(InputState previousState)
	{
		inputSource.FrameStart(previousState);
		currentState = inputSource.State;
		target.LogInput(currentState);
	}

	public InputState State
	{
		get
		{
			return currentState;
		}
	}
}

